---
title: "EDA"
author: "David Leshchiner"
date: "4/23/2021"
output: pdf_document
---

# Necessary Libraries

```{r}
library(tidyverse)
```


# Loading Data

```{r}
CovidData <- read.csv("./data/CovidDataSetFinal.csv")

CovidDataFiltered <- CovidData[, c("MaskWearingCategory","Population","PercentUnemployed","MedianHouseholdIncome","PercentAfricanAmerican","PercentHispanic", "PercentNativeAmericanAndAlaskaNative","PercentNativeHawaiianAndOtherPacificIslander","StatewideMaskRequirement","PercAdultsWithSomeCollegeOrAssociateDegree","PercAdultsWithBachelorDegreeOrHigher","per_dem2016","per_gop2016","per_gop2020","per_dem2020")]

attach(CovidDataFiltered)
```
# Summary Statistics

```{r}
head(CovidDataFiltered)
```
```{r}
CovidDataFiltered$StatewideMaskRequirement <- as.factor(CovidDataFiltered$StatewideMaskRequirement)
CovidDataFiltered$MaskWearingCategory <- as.factor(CovidDataFiltered$MaskWearingCategory)
summary(CovidDataFiltered)
```

```{r}
pairs(CovidDataFiltered)
```
```{r}
cor(CovidDataFiltered[1:8, 10:15])
```
# Data Visualization

```{r}
library(ggplot2)
```

### Education & Wealth

```{r}
CovidDataFiltered %>% 
  ggplot(aes(MaskWearingCategory, PercAdultsWithBachelorDegreeOrHigher, fill = StatewideMaskRequirement)) +
  geom_violin() +
  theme_bw()

CovidDataFiltered %>% 
  ggplot(aes(MaskWearingCategory, PercAdultsWithSomeCollegeOrAssociateDegree, fill = StatewideMaskRequirement)) +
  geom_violin() +
  theme_bw()

CovidDataFiltered %>% 
  ggplot(aes(MaskWearingCategory, MedianHouseholdIncome, fill = StatewideMaskRequirement)) +
  geom_violin() +
  theme_bw()
```
### Political Affiliation

```{r}
CovidDataFiltered %>% 
  ggplot(aes(MaskWearingCategory, per_dem2020, fill = StatewideMaskRequirement)) +
  geom_violin() +
  theme_bw()

CovidDataFiltered %>% 
  ggplot(aes(MaskWearingCategory, per_gop2020, fill = StatewideMaskRequirement)) +
  geom_violin() +
  theme_bw()
```

### Racial Minority Groups

```{r}
CovidDataFiltered %>% 
  ggplot(aes(MaskWearingCategory, PercentAfricanAmerican)) +
  geom_violin() +
  theme_bw()

CovidDataFiltered %>% 
  ggplot(aes(MaskWearingCategory, PercentHispanic)) +
  geom_violin() +
  theme_bw()

CovidDataFiltered %>% 
  ggplot(aes(MaskWearingCategory, PercentNativeAmericanAndAlaskaNative)) +
  geom_violin() +
  theme_bw()
```










