---
title: "KNN"
author: "David Leshchiner"
date: "4/23/2021"
output: pdf_document
---

# Necessary Libraries

```{r}
library(tidyverse)
library(class)
```


# Loading Data

```{r}
CovidData <- read.csv("./data/CovidDataSetFinal.csv")
CovidData <- na.omit(CovidData)


CovidDataFiltered <- CovidData[, c("MaskWearingCategory","Population","PercentUnemployed","MedianHouseholdIncome","PercentAfricanAmerican","PercentHispanic", "PercentNativeAmericanAndAlaskaNative","PercentNativeHawaiianAndOtherPacificIslander","StatewideMaskRequirement","PercAdultsWithSomeCollegeOrAssociateDegree","PercAdultsWithBachelorDegreeOrHigher","per_dem2016","per_gop2016","per_gop2020","per_dem2020")]

attach(CovidDataFiltered)
```
```{r}
CovidDataFiltered
```


# Training & Testing Data

```{r}
n = nrow(CovidDataFiltered)
Z = sample(n, n/2)
Training = CovidDataFiltered[Z,]
Testing = CovidDataFiltered[-Z,]      
```

```{r}
dim(CovidDataFiltered)
dim(Training)
dim(Testing)
```

```{r}
TrainingX = Training[, 2:8, 10:15]
TestingX = Testing[, 2:8, 10:15] 
TrainingY = MaskWearingCategory[Z]
TestingK = MaskWearingCategory[-Z]
```

# KNN Analysis

```{r}
class.rate = rep(0, 25)
for (K in 1:25) {
  knn1 = knn(TrainingX, TestingX, TrainingY, K)
  class.rate[K] = mean(TestingK == knn1)
  }

class.rate
```

```{r}
plot(k, class.rate, type = "b", lwd = 5)
```
At K = 14 the classification rate is 94.04%
At K = 7 the classification rate


# Confusion Matrices

```{r}
knnresult <- knn(TrainingX, TestingX, TrainingY, 14)
table(TestingK, knnresult)
```

1042/1108 = 94.04


```{r}
knnresult <- knn(TrainingX, TestingX, TrainingY, 7)
table(TestingK, knnresult)
```
1029/1108 = 92.87%


# KNN Cross-Validation

```{r}
cv <- knn.cv(TrainingX, TrainingY, 14)
table(TestingK, cv)
```

1039/1108 = 93.77%

```{r}
cv <- knn.cv(TrainingX, TrainingY, 7)
table(TestingK, cv)
```

1036/1108 = 93.5%





