---
title: "Logistic Regression"
author: "Anthony Baron"
date: "4/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
##libraries needed
library(boot)
```

```{r}
#LOAD DATA

CovidData <- read.csv("./data/CovidDataSetFinal.csv")
CovidData = na.omit(CovidData)
##Points used include MaskWearingCategory,Population, PercentUnemployed, MedianHouseholdIncome, PercentAfricanAmerican, PercentHispanic PercentNativeAmericanAndAlaskaNative, PercentNativeHawaiianAndOtherPacificIslander, StatewideMaskRequirement(yes), PercAdultsWithSomeCollegeOrAssociateDegree, PercAdultsWithBachelorDegreeOrHigher,per_dem2016,per_gop2016,per_gop2020,per_dem2020,per_dem2016,per_gop2016,per_gop2020,per_dem2020

CovidDataFiltered = CovidData[, c("MaskWearingCategory","Population","PercentUnemployed","MedianHouseholdIncome","PercentAfricanAmerican","PercentHispanic", "PercentNativeAmericanAndAlaskaNative","PercentNativeHawaiianAndOtherPacificIslander","StatewideMaskRequirement","PercAdultsWithSomeCollegeOrAssociateDegree","PercAdultsWithBachelorDegreeOrHigher","per_dem2016","per_gop2016","per_gop2020","per_dem2020")]

attach(CovidDataFiltered)

```

```{r}
#CREATE TRAINING AND TESTING SET
n = nrow(CovidDataFiltered)
Z = sample(n,n/2)
covid.train = CovidDataFiltered[Z,]
covid.test = CovidDataFiltered[-Z,]
```

```{r}
###Chose best threshold for logistic regression
TPR = rep(0,100)
FPR = rep(0,100)

for(k in 1:100){
  covid.train.glm = glm(MaskWearingCategory~.,data = covid.train,family = "binomial")
  covid.test.predict = predict(covid.train.glm,covid.test, type="response" )
  Yhat = (covid.test.predict > k/100 )
  TPR[k] = sum( Yhat==1 & MaskWearingCategory==1 ) / sum( MaskWearingCategory == 1 )
  FPR[k] = sum( Yhat==1 & MaskWearingCategory==0 ) / sum( MaskWearingCategory == 0 )
}
plot(FPR, TPR, xlab="False positive rate", ylab="True positive rate", main="ROC curve")

lines(FPR, TPR)

###Result: best threshold is about 0.78 from ROC curve


```

```{r}
##################Predict now that best threshold is selected of 0.7

#Summary of the glm
summary(covid.train.glm)


covid.test.predict = predict( covid.train.glm, covid.test, type="response" )

CorrectPredict = 1*( covid.test.predict > 0.78 )
CategoryWearingMask = covid.test$MaskWearingCategory

#Confusion Table
table(CorrectPredict,CategoryWearingMask)


```

```{r}
###Doing cross validation
covid.full.glm = glm(MaskWearingCategory~.,data = CovidDataFiltered,family = "binomial")

covid.data.cv = cv.glm(CovidDataFiltered,covid.full.glm)
print(covid.data.cv)$delta[1]

```